name: Sonar scan


on:
  push:
    branches:
      - Shreya/xlpdf


jobs:
  build-and-analyze:
    runs-on: [ubuntu-latest]
    steps:
      - name: Chekout Source
        uses: actions/checkout@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: "https://sonarcloud.io/"
